# This worflow evaluates the completness of the coverage of the code

name: Evaluate

on:
  workflow_dispatch:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install -r ./requirements.txt
    - name: Evaluate Coverage
      # working-directory: ../
      env: 
        WANDB_DISABLED: true
      run: |
        echo "$PWD"
        pip install finetune-eval-harness --upgrade
        coverage run -m pytest
        # pytest tests/test_eval.py
        coverage report --fail-under 80
        