# This worflow evaluates the completness of the coverage of the code

name: Evaluate

on:
  workflow_dispatch:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    #- name: Install dependencies
    #  run: |
    #    pip install flake8 pytest pytest-cov
    #    pip install -r ./requirements.txt
    - name: Create Folder
      run: |
        mkdir /sample/directory
        pytest --cov-fail-under=80 tests
    #- name: Evaluate Coverage
    #  run: |
    #    pytest --cov-fail-under=80 tests
