name: Publish Docker image

on: 
  push: # Trigger workflow only on push events
    branches: # ... for these branches
      - main
      - master

jobs:
  build-docker:
    name: build docker container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.0.0
        
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/malteos/finetune-evaluation-harness
          tags: |
            type=raw,value=${{github.ref_name}}
            type=raw,value=${{github.sha}}
            type=raw,value=latest

      - name: Build and push
        id: build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
