# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        echo Installing dependencies ....
        pip install -r ./requirements.txt
    - name: Lint with flake8
      run: |
        echo Checking synatix errors in files ...
        # stop the build if there are Python syntax errors or undefined names
        flake8 ./hf_scripts/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # F63: assertion/comparison errors; F7: break statement outside loop; 
        # F82: undefined variables
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    - name: Test with pytest
      run: |
        echo Check the Basic Stability ...
        pytest -v ./tests/test_stability.py